import type { StoreConfig } from "@/types/menu";

/**
 * ══════════════════════════════════════════════════════════════
 *  TEK MERKEZİ YAPILANDIRMA DOSYASI
 *  Her yeni müşteri için SADECE bu dosyayı ve public/assets
 *  içindeki görselleri güncelleyip yeniden deploy edin.
 * ══════════════════════════════════════════════════════════════
 */
export const storeConfig: StoreConfig = {
  store: {
    name: "Kadirli Mozaik Künefe Katmer",
    slogan: "Gerçek künefe lezzeti, sıcak servis",
    logoUrl: "/assets/logo.jpg",
    bannerUrl: "/assets/banner.jpg",
    themeColor: "#D97706", // marka rengi (Hex) — Mozaik Künefe için sıcak turuncu
    currency: "₺",
  },

  contact: {
    wifi: {
      ssid: "Liman_Misafir",
      password: "liman2024",
    },
    instagramUsername: "mozaikkunefekadirli",
    phone: "0507 679 02 74 / 0328 082 02 74",
    phoneHref: "tel:+905076790274",
    whatsappNumber: "905076790274",
    googleReviewUrl: "https://maps.google.com/?q=Kadirli+Mozaik+K%C3%BCnefe+Katmer",
    mapsUrl: "https://maps.google.com/?q=Kadirli+Mozaik+Künefe+Katmer",
    workingHours: "Açılış 11:30 - Kapanış 01:00",
  },

  categories: [
    {
      id: "icecekler",
      name: "İçecekler",
      icon: "Coffee",
      products: [
        {
          id: "turk-kahvesi",
          name: "Türk Kahvesi",
          description: "Geleneksel Türk kahvesi, köpüklü ve taze çekim.",
          price: 30,
          imageUrl: "/assets/products/turk-kahvesi.jpg",
          tags: ["Sıcak"],
          isAvailable: true,
        },
        {
          id: "filtre-kahve",
          name: "Filtre Kahve",
          description: "Günlük çekim filtre kahve, dengeli aromalar.",
          price: 28,
          imageUrl: "/assets/products/filtre-kahve.jpg",
          tags: ["Sıcak"],
          isAvailable: true,
        },
        {
          id: "cay",
          name: "Çay",
          description: "Sıcak dem çay — ince belli bardakta servis.",
          price: 12,
          imageUrl: "/assets/products/cay.jpg",
          tags: ["Sıcak"],
          isAvailable: true,
        },
        {
          id: "ayran",
          name: "Ayran",
          description: "Serinletici yoğurtlu içecek, ev yapımı kıvamda.",
          price: 15,
          imageUrl: "/assets/products/ayran.jpg",
          tags: ["Soğuk"],
          isAvailable: true,
        },
        {
          id: "gazli-icecek",
          name: "Gazlı İçecek",
          description: "Kola, gazoz veya meyveli gazoz seçenekleri.",
          price: 20,
          imageUrl: "/assets/products/gazli-icecek.jpg",
          tags: ["Soğuk"],
          isAvailable: true,
        },
        {
          id: "limonata",
          name: "Ev Yapımı Limonata",
          description: "Taze sıkılmış limon ve hafif şeker dengesiyle.",
          price: 25,
          imageUrl: "/assets/products/limonata.jpg",
          tags: ["Soğuk"],
          isAvailable: true,
        },
      ],
    },
    {
      id: "tatlilar",
      name: "Tatlılar",
      icon: "IceCream",
      products: [
        {
          id: "sutlac",
          name: "Sütlaç",
          description: "Fırınlanmış sütlaç, hafif tarçınla servis edilir.",
          price: 45,
          imageUrl: "/assets/products/sutlac.jpg",
          tags: ["Klasik"],
          isAvailable: true,
        },
        {
          id: "kunefe-mini",
          name: "Mini Künefe",
          description: "Tek kişilik, sıcak ve çıtır künefe porsiyonu.",
          price: 95,
          imageUrl: "/assets/products/kunefe-mini.jpg",
          tags: ["Sıcak"],
          isAvailable: true,
        },
        {
          id: "katmer-mini",
          name: "Mini Katmer",
          description: "İçi hamur ve kaymaklı, üzerine ceviz serpilir.",
          price: 60,
          imageUrl: "/assets/products/katmer-mini.jpg",
          tags: ["Klasik"],
          isAvailable: true,
        },
        {
          id: "dondurma",
          name: "Dondurma",
          description: "Geleneksel Maraş dondurması — top veya porsiyon.",
          price: 35,
          imageUrl: "/assets/products/dondurma.jpg",
          tags: ["Soğuk"],
          isAvailable: true,
        },
        {
          id: "baklava",
          name: "Baklava (Porsiyon)",
          description: "Taze baklava porsiyonu, ince çıtır katmanlar.",
          price: 80,
          imageUrl: "/assets/products/baklava.jpg",
          tags: ["Şerbetli"],
          isAvailable: true,
        },
        {
          id: "cezerye",
          name: "Cezerye",
          description: "Havuç ve fıstıklı geleneksel tatlı atıştırmalık.",
          price: 30,
          imageUrl: "/assets/products/cezerye.jpg",
          tags: ["Atıştırmalık"],
          isAvailable: true,
        },
      ],
    },
    {
      id: "tuzlular",
      name: "Tuzlular",
      icon: "UtensilsCrossed",
      products: [
        {
          id: "lahmacun",
          name: "Lahmacun",
          description: "İnce hamur üzerine baharatlı kıyma, limon ve maydanoz.",
          price: 60,
          imageUrl: "/assets/products/lahmacun.jpg",
          tags: ["Ana"],
          isAvailable: true,
        },
        {
          id: "pide-peynirli",
          name: "Pide (Peynirli)",
          description: "Sıcak pide, erimiş peynir ile servis edilir.",
          price: 90,
          imageUrl: "/assets/products/pide-peynirli.jpg",
          tags: ["Ana"],
          isAvailable: true,
        },
        {
          id: "sigara-boregi",
          name: "Sigara Böreği",
          description: "İçerisinde peynir ve maydanozlu çıtır börekler.",
          price: 40,
          imageUrl: "/assets/products/sigara-boregi.jpg",
          tags: ["Atıştırmalık"],
          isAvailable: true,
        },
        {
          id: "patates-kizartmasi",
          name: "Patates Kızartması",
          description: "Sıcak ve çıtır, yanında sos seçenekleriyle.",
          price: 55,
          imageUrl: "/assets/products/patates-kizartmasi.jpg",
          tags: ["Atıştırmalık"],
          isAvailable: true,
        },
        {
          id: "karisik-tabaq",
          name: "Karışık Tabaq",
          description: "Meze çeşitleriyle paylaşmalık karışık tabaq.",
          price: 220,
          imageUrl: "/assets/products/karisik-tabaq.jpg",
          tags: ["Paylaşmalık"],
          isAvailable: true,
          isCustomOrder: true,
        },
      ],
    },
    {
      id: "kahvaltilik",
      name: "Kahvaltılıklar",
      icon: "Salad",
      products: [
        {
          id: "serpme-kahvalti",
          name: "Serpme Kahvaltı",
          description: "Zeytin, peynir, bal, kaymak ve taze ekmekle servis.",
          price: 250,
          imageUrl: "/assets/products/serpme-kahvalti.jpg",
          tags: ["Paylaşmalık"],
          isAvailable: true,
        },
        {
          id: "menemen",
          name: "Menemen",
          description: "Domates, biber ve yumurta ile hazırlanmış sıcak menemen.",
          price: 85,
          imageUrl: "/assets/products/menemen.jpg",
          tags: ["Sıcak"],
          isAvailable: true,
        },
        {
          id: "borek-tabaq",
          name: "Börek Tabağı",
          description: "Çeşitli börekler ve sıcak servis.",
          price: 120,
          imageUrl: "/assets/products/borek-tabaq.jpg",
          tags: ["Paylaşmalık"],
          isAvailable: true,
        },
      ],
    },
    {
      id: "menuler",
      name: "Menüler",
      icon: "Sandwich",
      products: [
        {
          id: "oglen-menusu",
          name: "Öğlen Menüsü (Tek Kişilik)",
          description: "Seçilen ana yemek + içecek + tatlı (küçük porsiyon).",
          price: 180,
          imageUrl: "/assets/products/oglen-menusu.jpg",
          tags: ["Ekonomik"],
          isAvailable: true,
        },
        {
          id: "paylasma-menusu",
          name: "Paylaşma Menüsü (2-3 Kişilik)",
          description: "Meze, ana yemek ve tatlı içeren paylaşmalık menü.",
          price: 420,
          imageUrl: "/assets/products/paylasma-menusu.jpg",
          tags: ["Paylaşmalık"],
          isAvailable: true,
          isCustomOrder: true,
        },
      ],
    },
  ],
};

export default storeConfig;
